# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
##
## netmask2cidr
##
# ---- original file header ----
#
# @summary
#   This function Returns cidr value of netmask provided.
#
#
Puppet::Functions.create_function(:'netmask2cidr') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    require 'ipaddr'

    raise(Puppet::ParseError, "netmask2cidr(): Wrong number of arguments " +
          "given (#{args.size} for 1)") if args.size != 1

	IPAddr.new(args[0]).to_i.to_s(2).count("1")
  
  end
end
